### ISSUE TITLE
Stuck at "Put your art here" step with Figma

### ISSUE THREAD

**Issue by arthurcoder** [jtholloran/shots#11]
I am stuck at "Put your art here" step with Figma. I select the layer named "Put your art here",  then select "File > Place Image". As a result screenshot of my app is displayed but the case of the phone disappears. Can you please explain how to do this with basic steps?

**Comment by houmie** [comment]
@arthurcoder I have the exact same problem, which makes the entire project useless. Have you found out how to solve it? Thank you!

**Comment by houmie** [comment]
Actually this is not a bug. Simply ignore that the mask isn't covering the screenshot in step 2.  Go to step 3 and you will that it is now showing correctly.

Awesome project, thank you!

**Comment by jtholloran** [comment]
Hey @arthurcoder, hopefully @houmie's response helped. Do you have the most recent Figma template? There shouldn't be anything that says "Put your art here". Attached is a screenshot of the component you should be dropping your art into. Closing for now.

<img width="617" alt="Figma_art" src="https://user-images.githubusercontent.com/571347/83439898-d50f7b80-a3f8-11ea-9de0-62f245e4cd9f.png">
