### ISSUE TITLE
iPhone 11 Pro Max screenshot does not scale correctly

### ISSUE THREAD

**Issue by wham** [jtholloran/shots#12]
Figma Desktop App release 86
shots 4.0

**Steps:**

1. Make a 1242x2688 iPhone Pro Max screenshot
2. Navigate to _2. EDIT THESE SYMBOLS_
3. Click on _iPhone_art/11ProMax/1_ and paste the screenshot from step 1
4. Navigate to _3. PREVIEW ARTBOARDS FOR EXPORT_ and observe the result

**Expected:** The whole screenshot is visible in _6.5-inch_iPhone_11ProMax/1_
**Actual:** The screenshot is only partially visible

![image](https://user-images.githubusercontent.com/448809/89745965-d0f08180-da6b-11ea-895f-d1de6ca4652b.png)

I tried placing the screenshot in different layers but no luck. What am I doing wrong please?

**Comment by JDMPiquard** [comment]
To solve this:
• go into page "2. EDIT THESE SYMBOLS"
• select the image/screenshot that is giving you trouble
• on the right hand panel, under the section "Constraints", change both to the option "Scale" (they probably defaulted to "Top" and "Left" - this is the cause of the issue)

Voilà!

before:
<img width="240" alt="Screen Shot 2020-09-09 at 9 51 57 AM" src="https://user-images.githubusercontent.com/8194176/92614884-247c0800-f282-11ea-87d5-3ef076cb8a14.png">

after:
<img width="238" alt="Screen Shot 2020-09-09 at 9 52 54 AM" src="https://user-images.githubusercontent.com/8194176/92614995-41b0d680-f282-11ea-8d84-5eec9da063e1.png">

**Comment by wham** [comment]
Thanks! This works very well.
