### ISSUE TITLE
Support for 6.5inch display?

### ISSUE THREAD

**Issue by yuzushioh** [jtholloran/shots#2]
Hi @jtholloran 
I am just wondering if you are going to support for apple's new 6.5 inch display. Thank you.

**Comment by michaelcohen** [comment]
We'd love that, too!

**Comment by nyeu** [comment]
For those who ask for 6.5 inch display, here's the workaround:

Go to the preview Artworks (3rd step), select where it says iPhone_X/1...5 and on the right you will see a panel where it says iPhone X. Select on that and choose the option iPhone XS Max.

You will probably have to resize the views to match/center the content.


<img width="238" alt="screen shot 2019-01-10 at 19 03 09" src="https://user-images.githubusercontent.com/7888779/50987613-66cbcf80-150a-11e9-99c9-714208a0567e.png">

**Comment by jtholloran** [comment]
Thanks everyone. Added support for this with v2.2!
