### ISSUE TITLE
10 Screenshots, instead of 5

### ISSUE THREAD

**Issue by dkcas11** [jtholloran/shots#3]
Hey,

Thanks a lot for the template, works great and easy.
Any chance the amount of templates could be bumped up from 5 to 10, since the App Store supports 10 screenshots in total, for each device?

Right now I have two files, with 5 each 🙂 

Regards

**Comment by jtholloran** [comment]
Thanks @dkcas11. Fixed with v2.2!

**Comment by dkcas11** [comment]
Nice, thanks a lot! 🙂
