### ISSUE TITLE
Is iPhone XS Max supported?

### ISSUE THREAD

**Issue by houmie** [jtholloran/shots#5]
Hi,

This is an amazing project. I was looking for something like this for a while.

Is iPhone XS Max supported? There is a workaround, but it's not so efficient, as it is placing an iPhoneX (much smaller) into the iPhoneXS Max background. Too much space wasted.

Is there a proper way of supporting this? Officially we need 6.5" (XS MAX) and 5.5" (8 Plus). The rest is scaled down automatically anyway.

I hope this project is still maintained.

Thanks,
Houman

**Comment by Tibbs** [comment]
The way is done at the moment is that iPhone X screenshots are used for both iPhone X and Xr. The iPhone Xr has the same resolution as the iPhone Xs Max.

**Comment by codeslubber** [comment]
I think there is a problem. I took the exported files and dragged them to the 6.5" tab and was told the dimensions were wrong. It wants 1242x2688. I cannot get the template to produce that size?

**Comment by codeslubber** [comment]
Never mind I am an idiot, it exports the right size.

**Comment by jtholloran** [comment]
@houmie Yes, the way @Tibbs explained it is correct. I didn't see a reason to use different iPhone X frames. They all look similar enough for the purpose of App Store screenshots. The template, however, does spit out all the necessary sizes for the XS and XR / XS Max. It might be good to have the template create an XS Max folder (even though the XR shots are the same size). Might clear up some confusion. I'll consider adding that to the template. Gonna close this out for now. Thanks.

**Comment by jarrodbell** [comment]
Note that I have just had a rejection from app store because I used iPhone X frame in the 6.5" screenshots. They said "Specifically, your 6.5-inch iPhone screenshots do not display the app in the correct device frame."

Would be great to get the latest device frames added!

**Comment by jtholloran** [comment]
@jarrodbell I've added iPhone XS Max frames in the latest version. Thanks!
