### ISSUE TITLE
Bizarre situation where one of the images exports as wrong size

### ISSUE THREAD

**Issue by codeslubber** [jtholloran/shots#6]
I have shots 3 and 4 showing here. I can see NO difference between the 2. Yet, if I export, 3 gives me a really low resolution and 4 gives me the proper one (1242x2488). I wasted a stupid amount of time trying to figure this out today. Could find no difference in the values in the inspector, and all the other images (1, 2, and 4) imported properly. Just need a clue as to how this could happen.

**Comment by jtholloran** [comment]
@codeslubber Need a bit more info. I'm not following any of this. Did you mean to attach a screenshot?

**Comment by codeslubber** [comment]
wow thanks for responding two months later, lol.. what are you not following? I will make a YouTube video and then link this to it..

**Comment by jtholloran** [comment]
Closing this for now, but will reopen if you can provide more detail. Thanks.
