### ISSUE TITLE
Missing screen sizes before export

### ISSUE THREAD

**Issue by klische** [jtholloran/shots#8]
In the preview artboards for export, I see the iPhone 678Plus, but there is no place to put screenshots for them in the "Edit these symbols" part. I'm not too familiar with Sketch, so perhaps I'm missing something?

**Comment by Jobrod** [comment]
Same here, can't manage to do that. @klische Did you find any solution yet?

**Comment by klische** [comment]
@Jobrod Unfortunately not. I don't think it exists in the Sketch file or was mistakenly removed in a recent commit.

**Comment by jtholloran** [comment]
Yeah, the template currently repurposes the iPhone 6,7,8 shots for 6,7,8 Plus. I figured for most apps, it’s just an unnecessary extra step to paste in shots for the Plus. I realize they’re more critical for some apps and it probably makes sense to add them.

**Comment by jtholloran** [comment]
Fixed with v4.0
